

server:
  port: 8282

# database setting
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpastudy
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    # log? ??? MariaDB ??? ??? (formatting)
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????...
      ddl-auto: update
    properties:
      hibernate:
        # SQL ?? ??? ??? ?? (???)
        format_sql: true
    database: mysql

# log level setting
logging:
  level:
    root: info
    com:
      spring:
        jpastudy: debug
    org:
      hibernate:
        SQL: debug